# Generated by Django 5.2.6 on 2025-09-16 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0002_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=20)),
                ('TEXTO', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Card',
        ),
    ]
