# Generated by Django 5.2.6 on 2025-09-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0004_alter_card2_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='TickerItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PROJ1_1_0_TICKERITEM',
            },
        ),
    ]
