# Generated by Django 5.2.6 on 2025-09-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0005_tickeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CARROSSEL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SIMBOLO', models.CharField(max_length=10)),
                ('PRECO', models.DecimalField(decimal_places=2, max_digits=10)),
                ('VARIACAO', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'PROJ1_1_0_CARROSSEL',
            },
        ),
        migrations.DeleteModel(
            name='TickerItem',
        ),
    ]
