# Generated by Django 5.2.6 on 2025-09-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0006_carrossel_delete_tickeritem'),
    ]

    operations = [
        migrations.CreateModel(
            name='DICIONARIO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CATEGORIA', models.CharField(max_length=50)),
                ('TEXTO', models.TextField()),
                ('IMAGEM', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'PROJ1_1_0_DICIONARIO',
            },
        ),
    ]
