# Generated by Django 5.2.6 on 2025-09-20 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0007_dicionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='dicionario',
            name='TITULO',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
