# Generated by Django 5.2.6 on 2025-09-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0009_alter_dicionario_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Renda Fixa', 'Renda Fixa'), ('Renda Variável', 'Renda Variável')], default='Renda Fixa', max_length=15)),
                ('descricao', models.TextField()),
                ('rentabilidade', models.TextField()),
                ('link_imagem', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Investimento',
                'verbose_name_plural': 'Investimentos',
                'ordering': ['tipo', 'nome'],
            },
        ),
    ]
