# Generated by Django 5.2.6 on 2025-10-24 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0010_investimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerguntaPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=300)),
                ('alternativa_um', models.CharField(max_length=300)),
                ('alternativa_dois', models.CharField(max_length=300)),
                ('alternativa_tres', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Pergunta de Perfil',
                'verbose_name_plural': 'Perguntas de Perfil',
                'db_table': 'PROJ1_1_0_PERGUNTA_PERFIL',
            },
        ),
    ]
