# Generated by Django 5.2.6 on 2025-09-16 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0003_card2_delete_card'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='card2',
            table='PROJ1_1_0_CARD2',
        ),
    ]
