# Generated by Django 5.2.6 on 2025-09-20 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proj_1_0', '0008_dicionario_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dicionario',
            name='TITULO',
            field=models.CharField(max_length=100),
        ),
    ]
